### ISSUE TITLE
updata to React18 have this problem 

### ISSUE THREAD

**Issue by fschenkun22** [websemantics/awesome-ant-design#78]
I am allrady set my root like this,  the root warrning disapear
```const root = ReactDOM.createRoot(document.getElementById('root'))
root.render(
  <Provider store={store}>
    <HashRouter>
      <App />
    </HashRouter>
  </Provider>
)

But when I use Antd ,this has apear again
react_devtools_backend.js:3973 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
    at Home (http://localhost:3000/static/js/bundle.js:3979:63)
    at Routes (http://localhost:3000/static/js/bundle.js:94030:5)
    at main
    at Basic (http://localhost:3000/static/js/bundle.js:21683:25)
    at Adapter (http://localhost:3000/static/js/bundle.js:21666:37)
    at section
    at BasicLayout (http://localhost:3000/static/js/bundle.js:21698:34)
    at Adapter (http://localhost:3000/static/js/bundle.js:21666:37)
    at section
    at BasicLayout (http://localhost:3000/static/js/bundle.js:21698:34)
    at Adapter (http://localhost:3000/static/js/bundle.js:21666:37)
    at App (http://localhost:3000/static/js/bundle.js:703:63)
    at Router (http://localhost:3000/static/js/bundle.js:93963:15)
    at HashRouter (http://localhost:3000/static/js/bundle.js:93472:5)
    at Provider (http://localhost:3000/static/js/bundle.js:90613:20)

**Comment by fschenkun22** [comment]
when I used ```import {  message, notification } from 'antd'  apear
